ipv4:
  enable: true
  url: https://api-ipv4.ip.sb/ip
ipv6:
  enable: true
  url: https://api-ipv6.ip.sb/ip

dns:
  name: alidns
  id: LTAI4FchkR6gejrsAQMyuM3n
  secret: 6Z2t3rL5LQpLgJ74CMIoXDQCaoXB84